name: Deploy

on: push

env:
  CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  make_amd64_wheels:
    name: Make wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pipx run cibuildwheel==2.12.0
        env:
          CIBW_ARCHS_MACOS: x86_64

      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  make_arm64_wheels:
    name: Make wheels on macos-12 for arm64
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pipx run cibuildwheel==2.12.0
        env:
          CIBW_ARCHS_MACOS: arm64

      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  upload_all:
    needs: [make_amd64_wheels, make_arm64_wheels, make_sdist]
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
